import React from 'react';
import { X, Trash2 } from 'lucide-react';
import type { Catalog, Page, Product } from '../../types';
export interface SavedCatalogDraft { id:string;name:string;createdAt:string;updatedAt?:string;catalog:Catalog;pages:Page[];products:Product[] }
type DraftSummary=Pick<SavedCatalogDraft,'id'|'name'|'createdAt'|'updatedAt'>;
export function CatalogDraftDialog({mode,catalog,pages,products,onClose,onLoad}:{mode:'save'|'load';catalog:Catalog;pages:Page[];products:Product[];onClose:()=>void;onLoad:(draft:SavedCatalogDraft)=>void}) {
 const [name,setName]=React.useState(catalog.name),[drafts,setDrafts]=React.useState<DraftSummary[]>([]),[busy,setBusy]=React.useState(true),[error,setError]=React.useState(''),[saved,setSaved]=React.useState(false);
 React.useEffect(()=>{let active=true;fetch('/api/storage-status?action=drafts',{credentials:'include',cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Taslaklar yüklenemedi.');if(active)setDrafts(d.drafts||[])}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[]);
 const save=async(id?:string,targetName=name)=>{if(id&&!window.confirm('“'+targetName+'” taslağının üzerine kaydedilsin mi? Önceki içeriği değiştirilecek.'))return;setBusy(true);setError('');try{const used=new Set(pages.flatMap(p=>[...(p.content.productIds||[]),...(p.content.blocks||[]).map(b=>b.productId).filter(Boolean)]));const r=await fetch('/api/storage-status?action=drafts',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,name:targetName,catalog,pages,products:products.filter(p=>used.has(p.id))})});const d=await r.json();if(!r.ok)throw Error(d.error||'Taslak kaydedilemedi.');setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Taslak kaydedilemedi.')}finally{setBusy(false)}};
 const remove=async(draft:DraftSummary)=>{if(!window.confirm('“'+draft.name+'” taslağı silinsin mi? Bu işlem geri alınamaz.'))return;setBusy(true);setError('');try{const r=await fetch('/api/storage-status?action=drafts&id='+encodeURIComponent(draft.id),{method:'DELETE',credentials:'include'});const d=await r.json();if(!r.ok)throw Error(d.error||'Taslak silinemedi.');setDrafts(current=>current.filter(item=>item.id!==draft.id))}catch(e){setError(e instanceof Error?e.message:'Taslak silinemedi.')}finally{setBusy(false)}};
 const load=async(id:string)=>{if(!window.confirm('Bu taslak düzenleme alanına açılsın mı? Kaydedilmemiş değişiklikleriniz varsa önce taslağa kaydedin.'))return;setBusy(true);setError('');try{const r=await fetch('/api/storage-status?action=drafts&id='+encodeURIComponent(id),{credentials:'include',cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Taslak açılamadı.');if(!d.draft?.catalog||!Array.isArray(d.draft.pages)||!Array.isArray(d.draft.products))throw Error('Taslak verisi geçersiz.');onLoad(d.draft)}catch(e){setError(e instanceof Error?e.message:'Taslak açılamadı.')}finally{setBusy(false)}};
 return <div role="dialog" aria-modal="true" aria-label={mode==='save'?'Taslağa kayıt et':'Taslak katalog'} className="fixed inset-0 z-[800] bg-[#0f203a]/40 flex items-center justify-center p-4" onKeyDown={e=>{if(e.key==='Escape'&&!busy)onClose()}}><div className="bg-white text-[#0f203a] rounded-2xl shadow-2xl w-full max-w-lg max-h-[85dvh] flex flex-col"><header className="flex items-center justify-between px-5 py-4 border-b"><h2 className="font-semibold">{mode==='save'?'Taslağa kayıt et':'Taslak katalog'}</h2><button disabled={busy} aria-label="Kapat" onClick={onClose} className="p-2"><X size={18}/></button></header><div className="p-5 overflow-auto">{error&&<p role="alert" className="text-sm text-red-600 mb-4">{error}</p>}{saved?<div role="status"><p>Taslak kaydedildi.</p><button onClick={onClose} className="field mt-4">Tamam</button></div>:<>{mode==='save'&&<form onSubmit={e=>{e.preventDefault();void save()}} className="space-y-4 mb-6"><label className="block text-sm">Yeni taslak adı<input autoFocus maxLength={100} required value={name} onChange={e=>setName(e.target.value)} className="field mt-2 w-full"/></label><p className="text-xs opacity-60">{pages.length} sayfa · Düzen, ürünler ve sayfa ayarları birlikte kaydedilir.</p><button disabled={busy||!name.trim()} className="field w-full bg-[#0f203a] text-white disabled:opacity-40">{busy?'Lütfen bekleyin…':'Yeni taslak olarak kaydet'}</button></form>}<h3 className="font-medium text-sm mb-3">Kayıtlı taslaklar</h3>{busy&&<p role="status" className="text-sm mb-3">Yükleniyor…</p>}{!busy&&!error&&!drafts.length&&<p className="text-sm opacity-60">Henüz kayıtlı taslak yok.</p>}<div className="space-y-2">{drafts.map(d=><div key={d.id} className="p-4 border rounded-xl"><span className="block font-medium break-words">{d.name}</span><span className="block text-xs opacity-50 mt-1">{new Date(d.updatedAt||d.createdAt).toLocaleString('tr-TR')}</span><div className="flex flex-wrap gap-2 mt-3"><button disabled={busy} onClick={()=>mode==='save'?save(d.id,d.name):load(d.id)} className="field text-xs disabled:opacity-40">{mode==='save'?'Üzerine kaydet':'Taslağı aç'}</button><button disabled={busy} onClick={()=>remove(d)} className="field text-xs text-red-600 disabled:opacity-40" aria-label={d.name+' taslağını sil'}><Trash2 size={13} className="inline mr-1"/>Sil</button></div></div>)}</div></>}</div></div></div>;
}
