import React from 'react';
import type { PageBlock, Product, ProductInfoSettings } from '../../types';
import { automaticField, catalogFields, resolveCatalogProduct } from '../shared/catalogManualFields';
const editableRows=(value:string)=>value.split(/\r?\n/).map(line=>line.split(' · ').map(cell=>cell.trim())).filter(row=>row.length===6);
const headings=['Taş','Karat','Adet','Renk','Berraklık','Şekil'];
export function ManualProductFields({block,product,info,onPatch,onReset}:{block:PageBlock;product:Product;info:ProductInfoSettings;onPatch:(patch:Partial<PageBlock>)=>void;onReset:()=>void}){
 const shown=resolveCatalogProduct(product,block,info);
 const update=(key:string,value:string|number)=>onPatch({manualFields:{...block.manualFields,[key]:value}});
 return <section className="border rounded-lg p-3 space-y-3"><h3 className="font-semibold text-sm">Ürün bilgileri · bu kart</h3>{catalogFields.filter(field=>info[field.flag]!==false&&(field.flag==='showName'||!!info[field.flag])).map(({key,label})=>{
 const auto=automaticField(info,key);const value=(shown as any)[key]??'';
 return <div key={key} className="space-y-2"><div className="flex justify-between gap-2 text-xs"><span>{label}</span><span className="opacity-60">{auto?'Sistemden otomatik':'Manuel'}</span></div>{auto?<p className="text-xs break-words whitespace-pre-wrap max-h-28 overflow-auto">{String(value)||'—'}</p>:key==='stoneDetails'?<><p className="text-xs opacity-60">Her satır bir taş grubudur.</p>{(editableRows(String(value)).length?editableRows(String(value)):[Array(6).fill('')]).map((row,index,rows)=><div key={index} className="border rounded p-2 space-y-2"><div className="grid grid-cols-2 gap-2">{headings.map((heading,column)=><label key={heading} className="text-xs">{heading}<input className="field mt-1" value={row[column]} onChange={e=>{const next=rows.map(r=>[...r]);next[index][column]=e.target.value;update(key,next.map(r=>r.join(' · ')).join('\n'))}}/></label>)}</div><button className="field" onClick={()=>update(key,rows.filter((_,i)=>i!==index).map(r=>r.join(' · ')).join('\n'))}>Satırı kaldır</button></div>)}<button className="field" onClick={()=>update(key,[...editableRows(String(value)),Array(6).fill('')].map(r=>r.join(' · ')).join('\n'))}>Taş satırı ekle</button></>:key==='price'?<input aria-label="Manuel fiyat" className="field" type="number" min="0" step="0.01" value={value} onChange={e=>{const amount=Number(e.target.value);if(Number.isFinite(amount)&&amount>=0)update(key,amount)}}/>:<textarea aria-label={`Manuel ${label}`} className="field min-h-16" value={String(value)} onChange={e=>update(key,e.target.value)}/>}</div>
 })}<p className="text-xs opacity-60">Manuel düzenlemek için Sayfa özelliklerinden ilgili alanın “Sistemden otomatik” tikini kaldırın.</p><button className="field" onClick={onReset}>Özellikleri resetle · bu kart</button></section>
}
